name: Build Windows App
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Create Dynamic Windows Project
        run: flutter create . --platforms=windows
      
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Get Packages
        run: flutter pub get
        
      - name: Build Windows Release
        run: flutter build windows --release
        
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Direct-App
          path: build\windows\x64\runner\Release\
